config/routes.rb
Lrsr::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}  
  
  namespace :admin do
    resources :events
    resources :newsletters
    resources :articles
    resources :trail_conditions
    resources :sponsors
    resources :contact_request_emails
    resources :twitter_feeds
    resources :albums do
      scope :module => 'albums' do
        resources :album_pictures
      end      
    end
    resources :contact_requests do
      collection do
        get 'received'
      end
    end
  end
  resources :admin   
  resources :albums
  resources :events
  resources :articles
  resources :trail_conditions
  resources :contact_requests
  resources :newsletters
  resources :memberships
  resources :maps
  resources :sponsors
  resources :executives
  resources :pings
  resources :twitter_feeds

  root :to => "welcome#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name, :start, :location
  
    named_scope :upcomming, :conditions => ["start >= ?", Time.now.utc.to_s(:db)], :order => 'start asc'
  
  def display_time
    self.start
  end
  
  def tweet
    begin
      b = Bitly.new('symingtonroad', 'R_50ed08c79b7d216360e2403ac3000528')
      url = "http://www.lrsr.ca/events/#{self.id}" 
      short = b.shorten(url)
      "#{self.name[0..125]} #{short.short_url}"     
    rescue Exception => e
      nil
    end    
  end  
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  
  def index
    if params['upcomming_events'] == '1' || params[:commit].blank?
      @events = Event.order('start desc').where("start >= ?", Time.now.utc.to_s(:db)).page params[:page]      
    else
      @events = Event.order('start desc').page params[:page]
    end
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.create(params[:event])
    if @event.save
      flash[:notice] = "You successfully created a new event."
      redirect_to admin_events_path
    else
      render 'new'
    end
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:notice] = "You successfully updated the event"
      redirect_to admin_events_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      flash[:notice] = "You successfully removed the event"
    else
      flash[:error] = "The event could not be removed, please try again."
    end
    redirect_to admin_events_path    
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def show
    @event = Event.find(params[:id])
  end
end

app/views/admin/events/_form.html.haml
%fieldset
  %ul
    %li.form-field.required
      = form.label :name
      = form.text_field :name, :maxlength=> 50
  
    %li.form-field.required
      = form.label :location
      = form.text_field :location, :maxlength=> 50
          
    %li.form-field.required
      = form.label :start
      = form.datetime_select :start    
      
    %li.form-field
      = form.label :details
      = form.text_area :details   

app/views/admin/events/_search.html.haml
%br
-form_for [:admin, Event.new], :builder => LrsrFormBuilder, :html => {:method => :get} do |f|
  =label_tag 'upcomming_events_only'
  =check_box_tag 'upcomming_events', '1', params['upcomming_events'] || params[:commit].blank?
  =f.submit 'filter'

app/views/admin/events/edit.html.haml
%div.form
  %h2="Edit: #{@event.name}: #{@event.start.to_formatted_s(:short_with_year)}"
  - form_for [:admin, @event], :builder => LrsrFormBuilder do |f|
    = f.error_messages
    = render :partial => "form", :object => f
    %br
    = submit_tag "Update", :class => "btn green left_float"
    
    = link_to "Cancel", admin_events_path, :class => "btn red left_float"
%br
%br

app/views/admin/events/index.html.haml
%h2
  Events

= link_to 'Create A New Event', new_admin_event_path, :class => 'btn blue left_float'
%br
%br
.clear_both
=render :partial => 'search'  
%br
%table.data
  %thead
    %tr
      %th
        Name
      %th
        Start
      %th
        Actions
  %tbody
    -@events.each do |event|
      %tr
        %td
          =event.name
        %td
          =event.display_time
        %td
          =action_images [:admin, event], :exclude => [:index]
  %tfoot
    %tr
      %td{:colspan => 3}
        = paginate @events

app/views/admin/events/new.html.haml
%div.form
  %h2 Create A New Event
  - form_for [:admin, @event], :builder => LrsrFormBuilder do |f|
    = f.error_messages
    = render :partial => "form", :object => f
    %br
    = submit_tag "Create", :class => "btn green left_float"
    
    = link_to "Cancel", admin_events_path, :class => "btn red left_float"
%br
%br  

app/views/admin/events/show.html.haml
%h2
  ="#{@event.name}: #{@event.start.strftime("%A, %B %d, %Y at %l:%M%p")}"
%h3 Location
=@event.location
%h3 Details
=simple_format @event.details