config/routes.rb
Lrsr::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}  
  
  namespace :admin do
    resources :events
    resources :newsletters
    resources :articles
    resources :trail_conditions
    resources :sponsors
    resources :contact_request_emails
    resources :twitter_feeds
    resources :albums do
      scope :module => 'albums' do
        resources :album_pictures
      end      
    end
    resources :contact_requests do
      collection do
        get 'received'
      end
    end
  end
  resources :admin   
  resources :albums
  resources :events
  resources :articles
  resources :trail_conditions
  resources :contact_requests
  resources :newsletters
  resources :memberships
  resources :maps
  resources :sponsors
  resources :executives
  resources :pings
  resources :twitter_feeds

  root :to => "welcome#index"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
  
  def index
    @events = Event.upcomming
    @articles = Article.front_page
    @trail_condition = TrailCondition.club_trails
    @newsletter = Newsletter.last
    @weather = Forcast.latest
    @tweets = TwitterFeed.new_if_needed
  end
end

app/views/welcome/index.html.haml
=render :partial => 'shared/share_links'
%table{:border => 0, :cellpadding => 0, :cellspacing => 0, :align => 'center', :width => '1024px'}
  %tr
    %td{:width => '680px', :valign => 'top'}
      - add_displayed = false
      - @articles.each_with_index do |a, i|
        %table{:width => '100%'}
          %tr
            %td
              .center.title.bold
                =a.try(:title)
              %br
              =image_tag(a.image(:medium), :style => 'float:right;padding:5px;padding-top:30px') if a.image_file_name
              =simple_format(a.try(:body))
              %br
        -if (i % 3 == 2) && !add_displayed
          - add_displayed = true
          :javascript
            google_ad_client = "ca-pub-8409006645899010";
            google_ad_slot = "5868927659";
            google_ad_width = 468;
            google_ad_height = 60;
          %br
          %br
    %td{:width => '10px'}
    %td{:width => '268px', :valign => 'top'}
      LRSR Sponsor:
      %br
      =link_to @sponsor.name, (@sponsor.url.blank? ? sponsors_path : @sponsor.url)
      %br
      %br
      %table{:border => 0, :cellspacing => 10, :cellpadding => 0, :width => "334px", :bgcolor => '#DCDCDC'}
        %tr
          %td
            .bold
              Lac du Bonnet, MB
              %br
            .time
              =@weather.try(:created_at).strftime("%A, %B %d at %l:%M%p")   
          %td{:align => 'left'}
            .bold
              - if @weather && @weather.forcast && @weather.valid?
                =@weather.forcast.condition['temp']
                &deg;C
          -if @weather && @weather.forcast && @weather.valid?
            %tr
              %td
                =@weather.sky_conditions
                %br
                High:      
                =@weather.forcast.forecasts.first['high']
                &deg;C
                %br
                Low:
                =@weather.forcast.forecasts.first['low']
                &deg;C
                %br
                Humidity:
                =@weather.forcast.atmosphere['humidity']
                ='%'        
                %br
                Sunrise:
                =@weather.forcast.astronomy.attributes['sunrise'].value
                %br
                Sunset:
                =@weather.forcast.astronomy.attributes['sunset'].value
              %td{:align => 'left'}
                =image_tag(@weather.sky_conditions_link)
          -else
            %tr
              %td
                Weather update not available
      %br
      %table.outline{:border => 1, :cellspacing => 0, :cellpadding => 10, :width => 334}
        %tr
          %td{:align => 'center'}  
            Trail Status
            =trail_status @trail_condition
            %br
            %br
            Newsletter
            =link_to @newsletter.name, @newsletter.newsletter.url                     
      %table{:border => 0, :cellspacing => 0, :cellpadding => 10, :width => 334}
        %tr
          %td                    
            %h3 Events
            -if @events.any?
              %ul
                -@events.each do |event|
                  %li
                    =link_to "#{event.name} on #{event.display_time}", event_path(event)
            -else
              No Scheduled Events
      %table{:border => 0, :cellspacing => 0, :cellpadding => 10, :width => 334}
        %tr
          %td
            %h3 Our Twitter Feed
            =render :partial => 'shared/twitter'

  %tr
    %td{:colspan => 2}

%br