config/routes.rb
Lrsr::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}  
  
  namespace :admin do
    resources :events
    resources :newsletters
    resources :articles
    resources :trail_conditions
    resources :sponsors
    resources :contact_request_emails
    resources :twitter_feeds
    resources :albums do
      scope :module => 'albums' do
        resources :album_pictures
      end      
    end
    resources :contact_requests do
      collection do
        get 'received'
      end
    end
  end
  resources :admin   
  resources :albums
  resources :events
  resources :articles
  resources :trail_conditions
  resources :contact_requests
  resources :newsletters
  resources :memberships
  resources :maps
  resources :sponsors
  resources :executives
  resources :pings
  resources :twitter_feeds

  root :to => "welcome#index"

end

app/models/contact_request.rb
class ContactRequest < ActiveRecord::Base
  validates_presence_of :name, :email, :subject, :message
  after_create :notify
  
  def notify
    Notifier.contact_request(self, ContactRequestEmail.all).deliver
  end
end

app/controllers/admin/contact_requests_controller.rb
class Admin::ContactRequestsController < AdminController
  
  def index
    @contact_requests = ContactRequest.order('id desc').page params[:page]
  end
  
  def show
    @contact_request = ContactRequest.find(params[:id])
    @contact_request.update_attribute(:received, true)
    load_new_contact_requests    
  end
  
  def destroy
    @contact_request = ContactRequest.find(params[:id])
    if @contact_request.destroy
      flash[:notice] = "You successfully removed the contact request"
    else
      flash[:error] = "The contact_request could not be removed, please try again."
    end
    redirect_to admin_contact_requests_path    
  end
end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController 
  
  def new
    @contact_request = ContactRequest.new
  end
  
  def create
    @contact_request = ContactRequest.new(params[:contact_request])
    if @contact_request.save
      flash[:notice] = "You have successfully submitted a contact request."
      redirect_to root_path
    else
      render 'new'
    end
  end
end

app/views/admin/contact_requests/index.html.haml
%h2
  Contact Request Emails
(When a vistor fills out the contact us form these people will receive an email nontification)
%br
= link_to 'Create A New Contact Request Email', new_admin_contact_request_email_path, :class => 'btn blue left_float'
%br
%br
%table.data.nolink
  %thead
    %tr
      %th
        Name
      %th
        Email
      %th
        Actions
    %tbody
      -ContactRequestEmail.all.each do |c|
        %tr
          %td
            =c.name
          %td
            =c.email
          %td
            =action_images [:admin, c], :exclude => [:index, :show]          
%h2
  Received Contact Requests          
%table.data.nolink
  %thead
    %tr
      %th
        Name
      %th
        Email
      %th
        Subject
      %th
        Received
      %th
        Actions
  %tbody.request
    -@contact_requests.each do |request|
      %tr{:style => "#{request.received? ? '' : 'font-weight:bold'}"}
        %td
          =link_to request.name, admin_contact_request_path(request)
        %td
          =link_to request.email, admin_contact_request_path(request)
        %td
          =link_to request.subject, admin_contact_request_path(request)
        %td
          =link_to request.created_at.strftime("%A, %B %d, %Y at %l:%M%p"), admin_contact_request_path(request)
        %td
          =action_images [:admin, request], :exclude => [:index, :edit]
  %tfoot
    %tr
      %td{:colspan => 5}
        = paginate @contact_requests

app/views/admin/contact_requests/show.html.haml
%h2
  ="Contact Request From #{@contact_request.name}(#{@contact_request.email}) on #{@contact_request.created_at.strftime("%A, %B %d, %Y at %l:%M%p")}"
%h3="Subject: #{@contact_request.subject}"
%br
=@contact_request.message