config/routes.rb
Lrsr::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}  
  
  namespace :admin do
    resources :events
    resources :newsletters
    resources :articles
    resources :trail_conditions
    resources :sponsors
    resources :contact_request_emails
    resources :twitter_feeds
    resources :albums do
      scope :module => 'albums' do
        resources :album_pictures
      end      
    end
    resources :contact_requests do
      collection do
        get 'received'
      end
    end
  end
  resources :admin   
  resources :albums
  resources :events
  resources :articles
  resources :trail_conditions
  resources :contact_requests
  resources :newsletters
  resources :memberships
  resources :maps
  resources :sponsors
  resources :executives
  resources :pings
  resources :twitter_feeds

  root :to => "welcome#index"

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  has_attached_file :newsletter, :storage => :s3, :s3_credentials => "#{RAILS_ROOT}/config/s3.yml", :path => "/:style/:filename"
  validates_attachment_presence :newsletter  
  validates_presence_of :name
  
  def tweet
    begin
      b = Bitly.new('symingtonroad', 'R_50ed08c79b7d216360e2403ac3000528')
      url = self.newsletter.url 
      short = b.shorten(url)
      "Newsletter: #{self.name[0..125]} #{short.short_url}"     
    rescue Exception => e
      nil
    end    
  end  
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < AdminController

  def index
    @newsletters = Newsletter.order('id desc').page params[:page]
  end
  
  def new
    @newsletter = Newsletter.new
  end
  
  def create
    @newsletter = Newsletter.new(params[:newsletter])
    if @newsletter.save
      flash[:notice] = "You successfully created a newsletter"
      redirect_to admin_newsletters_path
    else
      render 'new'
    end
  end
  
  def edit
    @newsletter = Newsletter.find(params[:id])
  end
  
  def update
    @newsletter = Newsletter.find(params[:id])    
    if @newsletter.update_attributes(params[:newsletter])
      flash[:notice] = 'You successfully updated the newsletter'
      redirect_to admin_newsletters_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @newsletter = Newsletter.find(params[:id])
    if @newsletter.destroy
      flash[:notice] = "You successfully deleted the newsletter"
    end
    redirect_to admin_newsletters_path    
  end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  
  def index
    @newsletters = Newsletter.order('id desc').page params[:page]
  end
end

app/views/admin/newsletters/_form.html.haml
%fieldset
  %ul
    %li.form-field.required
      = form.label :name
      = form.text_field :name, :maxlength=> 50
  
    %li.form-field
      = form.label :file
      = form.file_field :newsletter

app/views/admin/newsletters/edit.html.haml
%div.form
  %h2="Edit: #{@newsletter.name}"
  - form_for [:admin, @newsletter], :html => { :multipart => true },:builder => LrsrFormBuilder do |f|
    = f.error_messages
    = render :partial => "form", :object => f
    %br
    = submit_tag "Update", :class => "btn green left_float"
    
    = link_to "Cancel", admin_newsletters_path, :class => "btn red left_float"
%br
%br

app/views/admin/newsletters/index.html.haml
%h2 Newsletters
= link_to 'Upload A New Newsletter', new_admin_newsletter_path, :class => 'btn blue left_float'
%br
%br

%table.data
  %tr
    %th
      Name
    %th 
      File
    %th
      Actions
  -@newsletters.each do |newsletter|
    %tr
      %td
        =link_to newsletter.name, newsletter.newsletter.url
      %td
        =link_to newsletter.newsletter_file_name, newsletter.newsletter.url
      %td
        =action_images([:admin, newsletter], :exclude => [:show,:index])
  

app/views/admin/newsletters/new.html.haml
%div.form
  %h2 Upload A New Newsletter
  - form_for [:admin, @newsletter], :html => { :multipart => true },:builder => LrsrFormBuilder do |f|
    = f.error_messages
    = render :partial => "form", :object => f
    %br
    = submit_tag "Upload", :class => "btn green left_float"
    
    = link_to "Cancel", admin_newsletters_path, :class => "btn red left_float"
%br
%br